GIT-008 add my login to file
devopsfabric/gitplayground pull request #5
Opened 2024-07-31 11:04 UTC by vladoz77

add my login to file

2024-07-31 11:04 UTC, vladoz77 commented
add login to file

2024-07-31 11:07 UTC, vladoz77 commented
change name

2024-07-31 16:28 UTC, vladoz77 commented
change name

2024-08-01 08:18 UTC, Fedaho requested changes
Не соответствует нашему флоу имя бранчи

2024-08-01 08:24 UTC, Fedaho requested changes
не нравится мне этот код

2024-08-01 08:37 UTC, Fedaho requested changes

2024-08-01 08:37 UTC, Fedaho commented on README.md
> +* vladoz77
разбираюсь с review change

2024-08-01 08:37 UTC, Fedaho commented on README.md
> +* vladoz77
в самом коде

2024-08-01 10:27 UTC, denncraft commented
имя ветки должно быть
GIT-008-add-yourself-into-playground-repo
вроде )
денег нет, но ты держись

2024-08-01 10:55 UTC, closed without merging